"""Shared pytest configuration for the python-vsdx test suite.

Does two things:

1. Ensures ``src/`` is importable even when the package hasn't been
   ``pip install -e``'d yet — handy for one-liner runs during
   development and for the CI job before the editable install finishes.

2. Defines the corpus-fixture loader the rest of the suite relies on.
   Fixtures live at ``~/code/ooxml-reference-corpus/fixtures/vsdx/``
   with the ``.office.vsdx`` infix denoting "generated by the real
   Microsoft product". When the corpus is missing (e.g. CI without the
   volume mounted) every test that consumes a corpus fixture is
   skipped rather than failed — keeps the green CI contract intact
   while the fixtures are still being produced.
"""

from __future__ import annotations

import os
import sys
import zipfile
from pathlib import Path
from typing import Optional

import pytest

_REPO_ROOT = Path(__file__).resolve().parent.parent
_SRC = _REPO_ROOT / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))


def _default_corpus_root() -> Path:
    """Return the canonical reference-corpus VSDX directory.

    Overridable with the ``VSDX_CORPUS_ROOT`` env var for CI + custom
    checkouts. Respects ``~`` expansion.
    """
    override = os.environ.get("VSDX_CORPUS_ROOT")
    if override:
        return Path(override).expanduser().resolve()
    return Path("~/code/ooxml-reference-corpus/fixtures/vsdx").expanduser()


@pytest.fixture(scope="session")
def corpus_root() -> Path:
    """Directory that holds the ``*.office.vsdx`` ground-truth fixtures.

    If the directory does not exist the fixture still yields the path —
    individual tests use :func:`corpus_fixture` which skips cleanly
    when the specific fixture is missing.
    """
    return _default_corpus_root()


def corpus_fixture(name: str, root: Optional[Path] = None) -> Path:
    """Locate a corpus fixture by base filename.

    Accepts either ``empty`` or ``empty.office.vsdx`` spellings. Returns
    the resolved path; raises ``pytest.skip`` (via a ``pytest.skip``
    call the caller re-raises) if the fixture is absent.

    Keeping this as a plain function (not a fixture) lets parametrized
    tests reference fixtures by string name in their parameter list.
    """
    base = root or _default_corpus_root()
    candidate = base / name
    if not candidate.suffix:
        candidate = candidate.with_suffix(".office.vsdx")
    elif not name.endswith(".office.vsdx") and name.endswith(".vsdx"):
        candidate = base / (name.rsplit(".", 1)[0] + ".office.vsdx")
    if not candidate.exists():
        pytest.skip(
            f"corpus fixture missing: {candidate} — produce via MS Visio "
            f"and land at ~/code/ooxml-reference-corpus/fixtures/vsdx/"
        )
    return candidate


def read_part(fixture_path: Path, part_name: str) -> bytes:
    """Read a single OPC part out of a ``.vsdx`` zip by zip-entry name.

    Convenience for fidelity tests that only care about one part — e.g.
    ``read_part(fx, "visio/pages/page1.xml")`` to grab the page XML
    without materialising the whole package. Raises ``KeyError`` if the
    part is not present in the zip.
    """
    with zipfile.ZipFile(fixture_path) as zf:
        return zf.read(part_name)


def list_parts(fixture_path: Path) -> list[str]:
    """Return the sorted list of zip-entry names inside a fixture."""
    with zipfile.ZipFile(fixture_path) as zf:
        return sorted(zf.namelist())


# Re-export the helpers so test modules can ``from conftest import ...``.
__all__ = ["corpus_fixture", "corpus_root", "list_parts", "read_part"]
